name: myapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^17.0.1
  provider: ^6.1.5+1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  pinput: ^5.0.0
  fluttertoast: ^8.2.14
  file_picker: ^10.3.7
  pdf: ^3.11.3
  pdf_text: ^0.5.0
  cloud_firestore: ^6.1.0
  google_fonts: ^6.3.3
  flutter_internet_speed_test: ^1.5.0
  webview_flutter: ^4.13.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  http: ^1.6.0

flutter:
  uses-material-design: true
