services:
  - type: web
    name: mangalam-wifi-zone
    env: node
    plan: free
    region: oregon
    buildCommand: npm install express
    startCommand: node health-check.js
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: OC200_BASE_URL
        sync: false
      - key: OC200_USER
        sync: false
      - key: OC200_PASS
        sync: false